name: MsgLog
main: redcore\chat\Main
api: 4.0.0
version: 1.0.0
commands:
  getmsg:
    description: get player messages
    permission: use.getmsg
permissions:
  use.getmsg:
    default: op
